### ISSUE TITLE
Add contact info to user agent 

### ISSUE THREAD

**Issue by NotJoeMartinez** [NotJoeMartinez/chess-insights#12]
- Need to add contact info to headers
- Complete explanation on #9 
- Also see:
https://www.chess.com/announcements/view/breaking-change-user-agent-contact-info-required

**Comment by elidakirigo** [comment]
hi, I'd like to contribute to the documentation of this project.

**Comment by NotJoeMartinez** [comment]
this doesn't seem to be possible or enforced by the dev team
