### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by aberonni** [NotJoeMartinez/chess-insights#46]
It would be cool to filter the insights by date (ie. show data for last week, last month etc.). If you're interested, I might look into contributing a PR to add this.

**Comment by NotJoeMartinez** [comment]
All of the data needed to pull this off is available from the API the biggest obstacle for me is figuring out how to 
integrate it into the UI in a way that doesn't clutter everything. Suggested design patterns for this would be greatly appreciated. Thanks

**Comment by NotJoeMartinez** [comment]
Just added date filtering on  #49 
<img width="1282" alt="image" src="https://github.com/NotJoeMartinez/chess-insights/assets/39905973/c9cbd429-9e02-4a75-82fb-e6b1f9e2a366">

**Comment by aberonni** [comment]
That's cool! I was hoping to see them on the home page - for example, to answer the question "What's the most used opening in the last month?". 

If it helps, I can contribute a PR with the UI that you can build the functionality off of, or I can look into building it entirely (if it's something you would also think is valuable).
